language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build polar-api-v3.gemspec
  - gem install ./polar-api-v3-1.0.0.gem
