=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Polar::ActivityStepSample
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ActivityStepSample' do
  before do
    # run before each test
    @instance = Polar::ActivityStepSample.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ActivityStepSample' do
    it 'should create an instance of ActivityStepSample' do
      expect(@instance).to be_instance_of(Polar::ActivityStepSample)
    end
  end
  describe 'test attribute "steps"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
