=begin
#Polar Accesslink API

#Polar Accesslink API documentation

The version of the OpenAPI document: 3.40.0
Contact: b2bhelpdesk@polar.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

# Common files
require 'polar-api-v3/api_client'
require 'polar-api-v3/api_error'
require 'polar-api-v3/version'
require 'polar-api-v3/configuration'

# Models
require 'polar-api-v3/models/activity'
require 'polar-api-v3/models/activity_log'
require 'polar-api-v3/models/activity_step_sample'
require 'polar-api-v3/models/activity_step_samples'
require 'polar-api-v3/models/activity_zone_sample'
require 'polar-api-v3/models/activity_zone_samples'
require 'polar-api-v3/models/available_user_data'
require 'polar-api-v3/models/available_user_datas'
require 'polar-api-v3/models/created_webhook'
require 'polar-api-v3/models/created_webhook_data'
require 'polar-api-v3/models/duration_zone'
require 'polar-api-v3/models/error'
require 'polar-api-v3/models/exercise'
require 'polar-api-v3/models/exercise_hash_id'
require 'polar-api-v3/models/exercises'
require 'polar-api-v3/models/heart_rate'
require 'polar-api-v3/models/physical_information'
require 'polar-api-v3/models/physical_informations'
require 'polar-api-v3/models/register'
require 'polar-api-v3/models/sample'
require 'polar-api-v3/models/samples'
require 'polar-api-v3/models/transaction_location'
require 'polar-api-v3/models/user'
require 'polar-api-v3/models/user_extra_info'
require 'polar-api-v3/models/webhook_info'
require 'polar-api-v3/models/webhook_info_data'
require 'polar-api-v3/models/webhook_patch'
require 'polar-api-v3/models/webhook_payload'
require 'polar-api-v3/models/webhook_ping'
require 'polar-api-v3/models/webhook_request'
require 'polar-api-v3/models/webhook_type'
require 'polar-api-v3/models/zone'
require 'polar-api-v3/models/zones'

# APIs
require 'polar-api-v3/api/daily_activity_api'
require 'polar-api-v3/api/exercises_api'
require 'polar-api-v3/api/physical_info_api'
require 'polar-api-v3/api/pull_notifications_api'
require 'polar-api-v3/api/training_data_api'
require 'polar-api-v3/api/users_api'
require 'polar-api-v3/api/webhooks_api'

module Polar
  class << self
    # Customize default settings for the SDK using block.
    #   Polar.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
